### ISSUE TITLE
Unclear container error log

### ISSUE THREAD

**Issue by MarekLani** [toolboc/azure-iot-edge-device-container#2]
When we have started container with wrong connections string by mistake, the container error log did not provided clear error description and we have spent quite a long time trying to diagnose what is the source of error. 

We've started IoT Edge container with following command `docker run -it -d --privileged -e connectionString='<IoTHubDeviceConnectionString>' toolboc/azure-iot-edge-device-container`

Docker logs <containerId> showed following errors:
[INFO] - Starting Azure IoT Edge Security Daemon 
[INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b) 
[INFO] - Using config file: /etc/iotedge/config.yaml 
[INFO] - Using runtime network id azure-iot-edge 
[INFO] - Initializing the module runtime... 
[INFO] - Finished initializing the module runtime. 
[INFO] - Configuring /var/lib/iotedge as the home directory. 
[INFO] - Configuring certificates... 
[INFO] - Transparent gateway certificates not found, operating in quick start mode... 
[INFO] - Finished configuring certificates. 
[INFO] - Initializing hsm... 
[ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2541) Generating certificate and key for alias iotedged-workload-ca 
[INFO] - Finished initializing hsm. 
[INFO] - Detecting if configuration file has changed... 
[INFO] - Change to configuration file detected. 
[INFO] - Removing all modules... 
[INFO] - Finished removing modules. 
[INFO] - Provisioning edge device... 
[ERR!] - A provisioning error occurred. 
[ERR!] -     caused by: Provisioning error

Edge Agent itself is capable to surface connection string problems while it outputs 401 unauthorized error. Please if possible surface this information also within toolboc/azure-iot-edge-device-container logs

**Comment by toolboc** [comment]
@MarekLani , if you need access to the edgeAgent logs, they can be accessed by creating an interactive session with:

`sudo docker exec -it <azure-iot-edge-device-container ID> /bin/bash`

then once inside the azure-iot-edge-device-container instance:

` docker logs -f edgeAgent`
